# This config should be kept as similar as possible to the one at
# cluster/addons/gci/fluentd-gcp.yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-logging
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
    #kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      name: fluentd-logging
      namespace: kube-system
      labels:
        k8s-app: fluentd-logging
    spec:
      containers:
      - name: fluentd-logging
        image: gcr.io/google_containers/fluentd-elasticsearch:1.19
        # Change for production use. Use the environment variable to the URL of your production host.
        #env:
        #  - name: "ELASTICSEARCH_LOGGING_SERVICE_HOST"
        #    value: "http://elasticsearch-logging:9200"
        volumeMounts:
        - name: varlog
          mountPath: /var/log/
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/log/containers
          readOnly: true
        - name: fluentdposfiles
          mountPath: /var/lib/fluentd
        - name: dockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config-volume
          mountPath: /etc/td-agent
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/
      - name: varlibdockercontainers
        hostPath:
          path: /var/log/containers
      - name: fluentdposfiles
        hostPath:
          path: /tmp/fluentd
      - name: dockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config-volume
        configMap:
          name: fluentd-config
