apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data-pvc
  namespace: gitlab
  annotations:
    volume.beta.kubernetes.io/storage-class: quobyte
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-config-pvc
  namespace: gitlab
  annotations:
    volume.beta.kubernetes.io/storage-class: quobyte
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
spec:
  replicas: 1
  template:
    metadata:
      name: gitlab
      labels:
        name: gitlab
        version: 8.16.3
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:8.16.3-ce.1
        env:
        - name: GITLAB_OMNIBUS_CONFIG
          value: "external_url 'http://gitlab.k8s.aws.inovex.io'; gitlab_rails['lfs_enabled'] = true;"
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: ssh
          containerPort: 22
        volumeMounts:
          - mountPath: /srv/gitlab/config
            name: gitlab-config-pvc
          - mountPath: /srv/gitlab/data
            name: gitlab-data-pvc
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 180
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
        - name: gitlab-config-pvc
          persistentVolumeClaim:
            claimName: gitlab-config-pvc
        - name: gitlab-data-pvc
          persistentVolumeClaim:
            claimName: gitlab-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: gitlab
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
    - name: https
      port: 443
      protocol: TCP
    - name: ssh
      port: 22
      protocol: TCP
  selector:
    name: gitlab
