apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-pvc
  namespace: monitoring
  annotations:
    volume.beta.kubernetes.io/storage-class: quobyte
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
